In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

0

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_arr = arr[0:6]

In [15]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_arr[:] = 99

In [17]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
last_item = arr[-1:]
last_item

array([10])

In [20]:
last_item[0] = 2222222222

In [21]:
arr

array([        99,         99,         99,         99,         99,
               99,          6,          7,          8,          9,
       2222222222])

In [22]:
arr_copy = arr.copy()

In [23]:
arr

array([        99,         99,         99,         99,         99,
               99,          6,          7,          8,          9,
       2222222222])

In [24]:
arr_copy[:] = 0

In [25]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr

array([        99,         99,         99,         99,         99,
               99,          6,          7,          8,          9,
       2222222222])

In [27]:
import numpy as np

In [28]:
arr_2d = np.array([[5,10,1,15], [1,4,77,2], [8,22,3,5], [0,1,2,3]])

In [29]:
arr_2d

array([[ 5, 10,  1, 15],
       [ 1,  4, 77,  2],
       [ 8, 22,  3,  5],
       [ 0,  1,  2,  3]])

In [30]:
print(arr_2d[0])
print(arr_2d[0][0])

# or 

print(arr_2d[0,0])
print(arr_2d[1,2])

print(arr_2d[2][1] == arr_2d[2, 1])

[ 5 10  1 15]
5
5
77
True


In [31]:
arr_2d

array([[ 5, 10,  1, 15],
       [ 1,  4, 77,  2],
       [ 8, 22,  3,  5],
       [ 0,  1,  2,  3]])

In [32]:
#a = arr_2d[1:,1:].copy()
arr_2d[:2,3:]
# [rows, columns]

array([[15],
       [ 2]])

In [ ]:
arr_2d[0, :] = 22

In [ ]:
arr_2d

In [ ]:
arr0 = np.zeros((5,5))
print(arr0)

In [ ]:
arr0

In [ ]:
arr_len = arr0.shape[0]
print(arr0.shape)

In [ ]:
for i in range(arr_len):
    arr0[i] = i
    
print(arr0)

In [ ]:
print(arr0[[0, 2, 4]])

In [ ]:
arr = np.arange(0, 11)

In [ ]:
bool_arr = arr > 5

In [ ]:
print(arr[bool_arr])
arr[bool_arr] = 5
print(arr[bool_arr])

In [ ]:
arr

In [ ]:
arr[arr%2==0]

In [ ]:
print(arr[arr>=5])
print(arr[arr<3])

In [ ]:
arr = np.arange(0, 100)
arr

In [ ]:
arr = arr.reshape(10, 10)

In [ ]:
con = (arr > 10) & (arr<50) & (arr%2==0)


arr[con]