In [1]:
import numpy as np

In [7]:
arr = np.arange(1, 20)

In [ ]:
print(arr)

In [ ]:
print(arr + arr)
np.random.randint(1, 100, 4

In [ ]:
print(arr - arr)

In [ ]:
print(arr*arr)

In [ ]:
print(arr + 100)
print()
print(arr - 100)
print()
print(arr * 100)
print()
print(arr / 100)

In [ ]:
1/0

In [2]:
arr_zeros = np.zeros(10)

In [3]:
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr_zeros / arr_zeros

/tmp/ipykernel_5844/3162014623.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr_zeros / arr_zeros


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [5]:
1 / arr_zeros

/tmp/ipykernel_5844/2708226294.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr_zeros


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [8]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [9]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [10]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [11]:
np.max(arr), arr.max()

(19, 19)

In [12]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [13]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [6]:
m1 = np.arange(0, 10).reshape(2, 5)
m2 = np.arange(0, 10).reshape(2, 5)

print(m1)
print(m2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
m1+m2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])